---
title: "COVID-19 in South Africa"
description: |
  A new article created using the Distill format.
author:
  - name: Yunqi Chen
    url: +++
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(gridExtra)
library(lubridate)
library(kableExtra)
```

# Data Description



```{r}
#Tidy process
covidcase_raw <- read_csv(here::here("data", "owid-covid-data.csv")) %>% 
  filter(location == "South Africa",
         date > as.Date('2021-01-01'))

case <- covidcase_raw %>% 
  select(date, total_cases, new_cases, total_deaths,new_deaths)

test <- covidcase_raw %>% 
  select(total_tests_per_thousand, new_tests_per_thousand, positive_rate)

vaccine <- covidcase_raw %>% 
  select(total_vaccinations_per_hundred, people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred)
```

# COVID-19 Cases in South Africa

```{r}
case_month <- case %>% 
  mutate(month = month(date)) %>% 
  select(-date)

library(sparkline)
library(DT)
case_month %>% 
  group_by(month) %>% 
  summarise(avg_total_cases = scales::comma(round(mean(total_cases))),
            avg_new_cases = scales::comma(round(mean(new_cases))),
            new_cases_trend = spk_chr(total_cases, type = "line"),
            avg_total_deaths = scales::comma(round(mean(total_deaths))),
            avg_new_deaths = round(mean(new_deaths)),
            new_deaths_trend = spk_chr(new_deaths, type = "line")) %>% 
  select(-month) %>% 
  datatable(escape = FALSE, 
            options = list(columnDefs = list(list(className = 'dt-right', targets = 0:4))),
            colnames = c("Month", "Total Cases", "New Cases", "New Cases Trend in A Month","Total Deaths", "New deaths", "New Deaths Trend in A Month"),
            caption = "Average COVID-19 Cases and Deaths Cases by Months"
            
            ) %>%
  spk_add_deps()
```


```{r, eval=FALSE}
knitr::kable(case_avg_month,
             table.attr="class='xtab'",
             col.names = c("Month", "Total Cases", "New Cases", "Total Deaths", "New deaths"),
             align = "crrrr",
             caption = "Average COVID-19 Cases and Deaths Cases by Months") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) 


  summarise (`Deforestation in hectars` = mean (Deforestation, na.rm = TRUE),
              Min = min(Deforestation, na.rm = TRUE),
              Max = max(Deforestation, na.rm = TRUE),
             `Line graph` = spk_chr(Deforestation, type ="line"),
             `Boxplot` = spk_chr(Deforestation, type ="box"))%>%  
  datatable(escape = FALSE, options = c (list(pageLength = 10, digits = 2))) %>%
  spk_add_deps()
```

# Reference

Hannah Ritchie, Edouard Mathieu, Lucas Rodés-Guirao, Cameron Appel, Charlie Giattino, Esteban Ortiz-Ospina, Joe Hasell, Bobbie Macdonald, Diana Beltekian and Max Roser (2020) - "Coronavirus Pandemic (COVID-19)". Published online at OurWorldInData.org. Retrieved from: 'https://ourworldindata.org/coronavirus' [Online Resource]
